- name: git pull code
  git: repo={{ git_repo }} dest={{ remote_path }}{{ core_name }} force=yes version={{ git_branch }} update=yes accept_hostkey=yes
  # notify:
  #   - restart jetty

- name: create core.properties..
  template: src=core.properties.j2 dest={{ remote_path }}{{ core_name }}/core.properties group=solr